### ISSUE TITLE
Possible to pass through gridline colors?

### ISSUE THREAD

**Issue by jongravois** [asantibanez/livewire-charts#3]
I am trying to make a "dark-mode" chart so I need to customize the gridline colors. Is this possible?

**Comment by andymnewhouse** [comment]
I was able to do this with some css and tailwind css:

```css

// with tailwind
@media (prefers-color-scheme: dark) {
    .apexcharts-text.apexcharts-yaxis-label {
        @apply text-gray-300;
        fill: theme('colors.gray.300');
    }

    .apexcharts-text.apexcharts-xaxis-label {
        @apply text-gray-300;
        fill: theme('colors.gray.300');
    }
}

// without tailwind
@media (prefers-color-scheme: dark) {
    .apexcharts-text.apexcharts-yaxis-label {
        color: #d2d6dc;
        fill: #d2d6dc;
    }

    .apexcharts-text.apexcharts-xaxis-label {
        color: #d2d6dc;
        fill: #d2d6dc;
    }
}

```

My charts look like this:

<img width="1105" alt="Screen Shot 2020-11-26 at 4 01 45 PM" src="https://user-images.githubusercontent.com/6541180/100393851-b0d7d480-3000-11eb-8bea-63b4e31addf3.png">
